package domain

import (
	"time"

	"github.com/google/uuid"
)

// AlertType represents the type of regulatory alert
type AlertType string

const (
	AlertTypeWashTrading      AlertType = "WASH_TRADING"
	AlertTypeSpoofing         AlertType = "SPOOFING"
	AlertTypePriceManipulation AlertType = "PRICE_MANIPULATION"
	AlertTypeVolumeAnomaly    AlertType = "VOLUME_ANOMALY"
	AlertTypeLayering         AlertType = "LAYERING"
	AlertTypeFrontRunning     AlertType = "FRONT_RUNNING"
	AlertTypePumpAndDump      AlertType = "PUMP_AND_DUMP"
	AlertTypeTradeSuspension  AlertType = "TRADE_SUSPENSION"
	AlertTypeMarketCorruption AlertType = "MARKET_CORRUPTION"
	AlertTypeCompliance       AlertType = "COMPLIANCE_VIOLATION"
)

// AlertSeverity represents the severity level of an alert
type AlertSeverity string

const (
	AlertSeverityInfo       AlertSeverity = "INFO"
	AlertSeverityWarning    AlertSeverity = "WARNING"
	AlertSeverityCritical   AlertSeverity = "CRITICAL"
	AlertSeverityFreezeAssets AlertSeverity = "FREEZE_ASSETS"
)

// AlertStatus represents the current status of an alert
type AlertStatus string

const (
	AlertStatusOpen          AlertStatus = "OPEN"
	AlertStatusInvestigating AlertStatus = "INVESTIGATING"
	AlertStatusResolved      AlertStatus = "RESOLVED"
	AlertStatusDismissed     AlertStatus = "DISMISSED"
	AlertStatusEscalated     AlertStatus = "ESCALATED"
)

// Alert represents a regulatory alert generated by the surveillance system
type Alert struct {
	ID              uuid.UUID       `json:"id" db:"id"`
	Type            AlertType       `json:"type" db:"type"`
	Severity        AlertSeverity   `json:"severity" db:"severity"`
	Status          AlertStatus     `json:"status" db:"status"`
	ExchangeID      uuid.UUID       `json:"exchange_id" db:"exchange_id"`
	Symbol          string          `json:"symbol" db:"symbol"`
	AccountID       *string         `json:"account_id,omitempty" db:"account_id"`
	OrderID         *uuid.UUID      `json:"order_id,omitempty" db:"order_id"`
	TradeID         *uuid.UUID      `json:"trade_id,omitempty" db:"trade_id"`
	Title           string          `json:"title" db:"title"`
	Description     string          `json:"description" db:"description"`
	Evidence        AlertEvidence   `json:"evidence" db:"evidence"`
	RiskScore       float64         `json:"risk_score" db:"risk_score"`
	PatternConfidence float64       `json:"pattern_confidence" db:"pattern_confidence"`
	DetectedAt      time.Time       `json:"detected_at" db:"detected_at"`
	UpdatedAt       time.Time       `json:"updated_at" db:"updated_at"`
	ResolvedAt      *time.Time      `json:"resolved_at,omitempty" db:"resolved_at"`
	ResolvedBy      *uuid.UUID      `json:"resolved_by,omitempty" db:"resolved_by"`
	Resolution      *string         `json:"resolution,omitempty" db:"resolution"`
	AssignedTo      *uuid.UUID      `json:"assigned_to,omitempty" db:"assigned_to"`
	Notes           []AlertNote     `json:"notes,omitempty"`
	Tags            []string        `json:"tags,omitempty"`
	RelatedAlertIDs []uuid.UUID     `json:"related_alert_ids,omitempty"`
	AuditHash       string          `json:"audit_hash" db:"audit_hash"`
}

// AlertEvidence contains the supporting evidence for an alert
type AlertEvidence struct {
	TradeIDs      []uuid.UUID     `json:"trade_ids,omitempty"`
	OrderIDs      []uuid.UUID     `json:"order_ids,omitempty"`
	AccountIDs    []string        `json:"account_ids,omitempty"`
	TimeWindow    TimeWindow      `json:"time_window"`
	PriceData     []PricePoint    `json:"price_data,omitempty"`
	VolumeData    []VolumePoint   `json:"volume_data,omitempty"`
	PatternData   PatternData     `json:"pattern_data"`
	Screenshots   []string        `json:"screenshots,omitempty"`
	RawPackets    []string        `json:"raw_packets,omitempty"`
}

// TimeWindow represents a time period
type TimeWindow struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

// PricePoint represents a price data point
type PricePoint struct {
	Timestamp time.Time       `json:"timestamp"`
	Price     decimal.Decimal `json:"price"`
	Volume    decimal.Decimal `json:"volume"`
}

// VolumePoint represents a volume data point
type VolumePoint struct {
	Timestamp time.Time       `json:"timestamp"`
	Volume    decimal.Decimal `json:"volume"`
	Count     int             `json:"count"`
}

// PatternData contains pattern-specific data
type PatternData struct {
	PatternType       string          `json:"pattern_type"`
	PatternParameters map[string]any  `json:"pattern_parameters"`
	DetectionMethod   string          `json:"detection_method"`
	ThresholdsUsed    map[string]any  `json:"thresholds_used"`
	CalculatedValues  map[string]any  `json:"calculated_values"`
}

// AlertNote represents a note added to an alert
type AlertNote struct {
	ID          uuid.UUID `json:"id"`
	AlertID     uuid.UUID `json:"alert_id"`
	AuthorID    uuid.UUID `json:"author_id"`
	AuthorName  string    `json:"author_name"`
	Content     string    `json:"content"`
	CreatedAt   time.Time `json:"created_at"`
	IsInternal  bool      `json:"is_internal"`
}

// AlertFilter represents filter criteria for listing alerts
type AlertFilter struct {
	Types           []AlertType      `json:"types,omitempty"`
	Severities      []AlertSeverity  `json:"severities,omitempty"`
	Statuses        []AlertStatus    `json:"statuses,omitempty"`
	ExchangeIDs     []uuid.UUID      `json:"exchange_ids,omitempty"`
	Symbols         []string         `json:"symbols,omitempty"`
	AccountID       *string          `json:"account_id,omitempty"`
	DetectedAfter   *time.Time       `json:"detected_after,omitempty"`
	DetectedBefore  *time.Time       `json:"detected_before,omitempty"`
	MinRiskScore    *float64         `json:"min_risk_score,omitempty"`
	MaxRiskScore    *float64         `json:"max_risk_score,omitempty"`
	AssignedTo      *uuid.UUID       `json:"assigned_to,omitempty"`
	Tags            []string         `json:"tags,omitempty"`
}

// AlertStatistics represents aggregated statistics for alerts
type AlertStatistics struct {
	TotalAlerts        int64                    `json:"total_alerts"`
	OpenAlerts         int64                    `json:"open_alerts"`
	ResolvedAlerts     int64                    `json:"resolved_alerts"`
	AlertsByType       map[AlertType]int64      `json:"alerts_by_type"`
	AlertsBySeverity   map[AlertSeverity]int64  `json:"alerts_by_severity"`
	AlertsByStatus     map[AlertStatus]int64    `json:"alerts_by_status"`
	AverageResolutionTime time.Duration         `json:"average_resolution_time"`
	TopExchanges       []ExchangeAlertStats     `json:"top_exchanges"`
	TopSymbols         []SymbolAlertStats       `json:"top_symbols"`
	TrendData          []AlertTrendPoint        `json:"trend_data"`
}

// ExchangeAlertStats represents alert statistics for an exchange
type ExchangeAlertStats struct {
	ExchangeID    uuid.UUID `json:"exchange_id"`
	ExchangeName  string    `json:"exchange_name"`
	AlertCount    int64     `json:"alert_count"`
	CriticalCount int64     `json:"critical_count"`
}

// SymbolAlertStats represents alert statistics for a symbol
type SymbolAlertStats struct {
	Symbol     string `json:"symbol"`
	AlertCount int64  `json:"alert_count"`
	RiskScore  float64 `json:"risk_score"`
}

// AlertTrendPoint represents a data point for alert trends
type AlertTrendPoint struct {
	Timestamp   time.Time         `json:"timestamp"`
	AlertCount  int64             `json:"alert_count"`
	ByType      map[AlertType]int64 `json:"by_type"`
	BySeverity  map[AlertSeverity]int64 `json:"by_severity"`
}

// AlertThreshold represents configurable thresholds for alert generation
type AlertThreshold struct {
	ID              uuid.UUID     `json:"id"`
	Name            string        `json:"name"`
	AlertType       AlertType     `json:"alert_type"`
	Enabled         bool          `json:"enabled"`
	Severity        AlertSeverity `json:"severity"`
	Parameters      map[string]any `json:"parameters"`
	MinConfidence   float64       `json:"min_confidence"`
	CooldownPeriod  time.Duration `json:"cooldown_period"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	UpdatedBy       uuid.UUID     `json:"updated_by"`
}
